#!/bin/sh

cd /app/asouldocs

# Link volumed data with app data
ln -sfn /data/asouldocs/log  ./log
ln -sfn /data/asouldocs/custom ./custom

chown -R asouldocs:asouldocs /data/asouldocs /app/asouldocs
chmod 0755 /data /data/asouldocs
